config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

  resource :checklist, only: [:show, :edit, :update] do
    member do
      get 'download'
      get 'print'
    end
  end

  namespace :admin do
    root 'home#index'
    resources :presidents
    resources :vice_presidents
    resources :parties
    resources :party_lists
    resources :senators
  end
end

app/models/senator.rb
class Senator < ActiveRecord::Base
  validates :name, presence: true
  validates :ballot_name, presence: true
  validates :ballot_number, presence: true, uniqueness: true,
    numericality: { only_integer: true, greater_than: 0 }

  belongs_to :party
  has_and_belongs_to_many :checklists

  def name_with_ballot_number
    "#{ballot_number}. #{ballot_name}"
  end
end

app/controllers/admin/senators_controller.rb
class Admin::SenatorsController < Admin::BaseController
  def index
    @senators = Senator.all
  end

  def show
    @senator = Senator.find(params[:id])
  end

  def new
    @senator = Senator.new
    @parties = Party.all
  end

  def create
    @senator = Senator.new(senator_params)
    @parties = Party.all

    if @senator.save
      redirect_to [:admin, @senator]
    else
      render :new
    end
  end

  def edit
    @senator = Senator.find(params[:id])
    @parties = Party.all
  end

  def update
    @senator = Senator.find(params[:id])
    @parties = Party.all

    if @senator.update_attributes(senator_params)
      redirect_to [:admin, @senator]
    else
      render :edit
    end
  end

  def destroy
    @senator = Senator.find(params[:id])

    if @senator.destroy
      redirect_to admin_senators_path
    else
      redirect_to [:admin, @senator]
    end
  end

  private
    def senator_params
      params.require(:senator).permit(:name, :ballot_name, :ballot_number, :party_id)
    end
end

app/views/admin/senators/_form.html.haml
= form_for [:admin, @senator] do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :ballot_name
    = f.text_field :ballot_name, class: 'form-control'

  .form-group
    = f.label :ballot_number
    = f.text_field :ballot_number, class: 'form-control'

  .form-group
    = f.label :party_id, 'Party'
    = f.select :party_id, options_from_collection_for_select(@parties, :id, :name), {}, class: 'form-control'

  .form-group
    = f.submit class: 'btn btn-primary form-control'

app/views/admin/senators/_senator.html.haml
%li
  = link_to senator.name, admin_senator_path(senator)

app/views/admin/senators/edit.html.haml
= link_to 'Back', admin_senator_path(@senator)

= render 'form'

app/views/admin/senators/index.html.haml
%ul
  = render partial: 'senator', collection: @senators, as: :senator

= link_to 'Create new senator', new_admin_senator_path

app/views/admin/senators/new.html.haml
= link_to 'Back', admin_senators_path

= render 'form'

app/views/admin/senators/show.html.haml
%h2 #{@senator.name}
%h3 #{@senator.ballot_name}
%h3 #{@senator.ballot_number}
%h3 #{@senator.party.name }

= link_to 'Back', admin_senators_path
= link_to 'Edit', edit_admin_senator_path(@senator)
= link_to 'Delete', admin_senator_path(@senator), data: {confirm: "Are you sure you want to delete #{@senator.name}?"}, method: :delete