config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

  resource :checklist, only: [:show, :edit, :update] do
    member do
      get 'download'
      get 'print'
    end
  end

  namespace :admin do
    root 'home#index'
    resources :presidents
    resources :vice_presidents
    resources :parties
    resources :party_lists
    resources :senators
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
    @user_count = User.count
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def index
    if user_signed_in?
      redirect_to edit_checklist_path and return
    end
  end

  def resource_name
    :user
  end

  def resource_class
    User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.haml
.loginBg
%ul.cb-slideshow
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
  %li
    %span
.loginWrapper
  .row
    .col-md-6
      .loginLeftContent
        .logo
        %p Maging handa ngayong darating na eleksyon. Create your computerized kodigo with Balota2016 to help you remember who you want to vote for, help prevent overvoting, and to remind you who you voted for when you're checking your voting receipt. VOTE WISELY!

        %p Note: We won't be collecting any sensitive data. This web app will simply help you create your list.
    .col-md-6
      .loginRightContent
        = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|

          .form-group
            = f.text_field :username, autofocus: true, placeholder: 'Username', class: 'form-control'
          .form-group
            = f.password_field :password, autocomplete: "off", placeholder: 'Password', class: 'form-control'
          - if devise_mapping.rememberable?
            .form-group
              = f.check_box :remember_me
              = f.label :remember_me
          .form-group.buttons
            = link_to "Register", new_registration_path(resource_name)
            = f.submit "Log in", class: 'btn'

          .lineSeparator
            .or or

        - if devise_mapping.omniauthable?
          - resource_class.omniauth_providers.each do |provider|
            = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), :class => "btn fbLogin"