config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

  resource :checklist, only: [:show, :edit, :update] do
    member do
      get 'download'
      get 'print'
    end
  end

  namespace :admin do
    root 'home#index'
    resources :presidents
    resources :vice_presidents
    resources :parties
    resources :party_lists
    resources :senators
  end
end

app/models/president.rb
class President < ActiveRecord::Base
  validates :name, presence: true
  validates :ballot_name, presence: true
  validates :ballot_number, presence: true, uniqueness: true,
    numericality: { only_integer: true, greater_than: 0 }

  belongs_to :party
  has_many :checklists

  def name_with_ballot_number
    "#{ballot_number}. #{ballot_name}"
  end
end

app/controllers/admin/presidents_controller.rb
class Admin::PresidentsController < Admin::BaseController
  def index
    @presidents = President.all
  end

  def show
    @president = President.find(params[:id])
  end

  def new
    @president = President.new
    @parties = Party.all
  end

  def create
    @president = President.new(president_params)
    @parties = Party.all

    if @president.save
      redirect_to [:admin, @president]
    else
      render :new
    end
  end

  def edit
    @president = President.find(params[:id])
    @parties = Party.all
  end

  def update
    @president = President.find(params[:id])
    @parties = Party.all

    if @president.update_attributes(president_params)
      redirect_to [:admin, @president]
    else
      render :edit
    end
  end

  def destroy
    @president = President.find(params[:id])

    if @president.destroy
      redirect_to admin_presidents_path
    else
      redirect_to [:admin, @president]
    end
  end

  private
    def president_params
      params.require(:president).permit(:name, :ballot_name, :ballot_number, :party_id)
    end
end

app/views/admin/presidents/_form.html.haml
= form_for [:admin, @president] do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :ballot_name
    = f.text_field :ballot_name, class: 'form-control'

  .form-group
    = f.label :ballot_number
    = f.text_field :ballot_number, class: 'form-control'

  .form-group
    = f.label :party_id, 'Party'
    = f.select :party_id, options_from_collection_for_select(@parties, :id, :name), {}, class: 'form-control'

  .form-group
    = f.submit class: 'btn btn-primary form-control'

app/views/admin/presidents/_president.html.haml
%li
  = link_to president.name, admin_president_path(president)

app/views/admin/presidents/edit.html.haml
= link_to 'Back', admin_president_path(@president)

= render 'form'

app/views/admin/presidents/index.html.haml
%ul
  = render partial: 'president', collection: @presidents, as: :president

= link_to 'Create new President', new_admin_president_path

app/views/admin/presidents/new.html.haml
= link_to 'Back', admin_presidents_path

= render 'form'

app/views/admin/presidents/show.html.haml
%h2 #{@president.name}
%h3 #{@president.ballot_name}
%h3 #{@president.ballot_number}
%h3 #{@president.party.name }

= link_to 'Back', admin_presidents_path
= link_to 'Edit', edit_admin_president_path(@president)
= link_to 'Delete', admin_president_path(@president), data: {confirm: "Are you sure you want to delete #{@president.name}?"}, method: :delete