config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

  resource :checklist, only: [:show, :edit, :update] do
    member do
      get 'download'
      get 'print'
    end
  end

  namespace :admin do
    root 'home#index'
    resources :presidents
    resources :vice_presidents
    resources :parties
    resources :party_lists
    resources :senators
  end
end

app/models/vice_president.rb
class VicePresident < ActiveRecord::Base
  validates :name, presence: true
  validates :ballot_name, presence: true
  validates :ballot_number, presence: true, uniqueness: true,
    numericality: { only_integer: true, greater_than: 0 }

  belongs_to :party
  has_many :checklists

  def name_with_ballot_number
    "#{ballot_number}. #{ballot_name}"
  end
end

app/controllers/admin/vice_presidents_controller.rb
class Admin::VicePresidentsController < Admin::BaseController
  def index
    @vice_presidents = VicePresident.all
  end

  def show
    @vice_president = VicePresident.find(params[:id])
  end

  def new
    @vice_president = VicePresident.new
    @parties = Party.all
  end

  def create
    @vice_president = VicePresident.new(vice_president_params)
    @parties = Party.all

    if @vice_president.save
      redirect_to [:admin, @vice_president]
    else
      render :new
    end
  end

  def edit
    @vice_president = VicePresident.find(params[:id])
    @parties = Party.all
  end

  def update
    @vice_president = VicePresident.find(params[:id])
    @parties = Party.all

    if @vice_president.update_attributes(vice_president_params)
      redirect_to [:admin, @vice_president]
    else
      render :edit
    end
  end

  def destroy
    @vice_president = VicePresident.find(params[:id])

    if @vice_president.destroy
      redirect_to admin_vice_presidents_path
    else
      redirect_to [:admin, @vice_president]
    end
  end

  private
    def vice_president_params
      params.require(:vice_president).permit(:name, :ballot_name, :ballot_number, :party_id)
    end
end

app/views/admin/vice_presidents/_form.html.haml
= form_for [:admin, @vice_president] do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :ballot_name
    = f.text_field :ballot_name, class: 'form-control'

  .form-group
    = f.label :ballot_number
    = f.text_field :ballot_number, class: 'form-control'

  .form-group
    = f.label :party_id, 'Party'
    = f.select :party_id, options_from_collection_for_select(@parties, :id, :name), {}, class: 'form-control'

  .form-group
    = f.submit class: 'btn btn-primary form-control'

app/views/admin/vice_presidents/_vice_president.html.haml
%li
  = link_to vice_president.name, admin_vice_president_path(vice_president)

app/views/admin/vice_presidents/edit.html.haml
= link_to 'Back', admin_vice_president_path(@vice_president)

= render 'form'

app/views/admin/vice_presidents/index.html.haml
%ul
  = render partial: 'vice_president', collection: @vice_presidents, as: :vice_president

= link_to 'Create new Vice President', new_admin_vice_president_path

app/views/admin/vice_presidents/new.html.haml
= link_to 'Back', admin_vice_presidents_path

= render 'form'

app/views/admin/vice_presidents/show.html.haml
%h2 #{@vice_president.name}
%h3 #{@vice_president.ballot_name}
%h3 #{@vice_president.ballot_number}
%h3 #{@vice_president.party.name }

= link_to 'Back', admin_vice_presidents_path
= link_to 'Edit', edit_admin_vice_president_path(@vice_president)
= link_to 'Delete', admin_vice_president_path(@vice_president), data: {confirm: "Are you sure you want to delete #{@vice_president.name}?"}, method: :delete